import { v4 as uuidv4 } from 'uuid';
export default [
  {
    id: 0,
    uuid: uuidv4(),
    name: 'Rags',
    desc: 'Rags provided basic protection.',
    defence: 2,
    state: 'none',
    price: '-1',
  },
  {
    id: 1,
    uuid: uuidv4(),
    name: 'Leather Armor',
    desc: 'Leather Armor provides basic protection.',
    defence: 5,
    state: 'none',
    price: '50',
  },
  {
    id: 2,
    uuid: uuidv4(),
    name: 'Chainmail Armor',
    desc: 'Chainmail Armor offers moderate protection.',
    defence: 10,
    state: 'none',
    price: '100',
  },
  {
    id: 3,
    uuid: uuidv4(),
    name: 'Plate Armor',
    desc: 'Plate Armor provides strong protection.',
    defence: 15,
    state: 'none',
    price: '200',
  },
  {
    id: 4,
    uuid: uuidv4(),
    name: 'Mythril Armor',
    desc: 'Mythril Armor offers exceptional protection.',
    defence: 20,
    state: 'none',
    price: '500',
  },
  {
    id: 5,
    uuid: uuidv4(),
    name: 'Dragon Scale Armor',
    desc: 'Dragon Scale Armor provides ultimate protection.',
    defence: 25,
    state: 'none',
    price: '1000',
  },
];
