import { v4 as uuidv4 } from 'uuid';
export default [
  {
    id: 0,
    uuid: uuidv4(),
    name: 'Rags',
    desc: 'Rags provided basic protection.',
    attack: 0,
    defence: 2,
    state: 'none',
    price: '-1',
  },
  {
    id: 1,
    uuid: uuidv4(),
    name: 'Leather Armor',
    desc: 'Leather Armor provides basic protection.',
    attack: 0,
    defence: 5,
    state: 'none',
    price: '50',
  },
  {
    id: 2,
    uuid: uuidv4(),
    name: 'Trader Suit',
    desc: 'Trader Suit provides basic protection against radiation.',
    attack: 0,
    defence: 25,
    state: 'none',
    price: '1000',
  },
  {
    id: 3,
    uuid: uuidv4(),
    name: 'Radiation Suit',
    desc: 'Radiation Suit provides ultimate protection against radiation.',
    attack: 0,
    defence: 25,
    state: 'none',
    price: '1000',
  },
  {
    id: 4,
    uuid: uuidv4(),
    name: 'Metal Armor',
    desc: 'Metal Armor provides strong protection.',
    attack: 0,
    defence: 10,
    state: 'none',
    price: '100',
  },
  {
    id: 5,
    uuid: uuidv4(),
    name: 'Raider Armor',
    desc: 'Raider Armor provides strong protection.',
    attack: 0,
    defence: 10,
    state: 'none',
    price: '100',
  },
  {
    id: 6,
    uuid: uuidv4(),
    name: 'Plate Armor',
    desc: 'Plate Armor provides strong protection.',
    attack: 0,
    defence: 15,
    state: 'none',
    price: '200',
  },
  {
    id: 7,
    uuid: uuidv4(),
    name: 'Battle Armor',
    desc: 'Battle Armor provides ultimate protection.',
    attack: 0,
    defence: 20,
    state: 'none',
    price: '500',
  },
  {
    id: 8,
    uuid: uuidv4(),
    name: 'Military Armor',
    desc: 'Military Armor provides ultimate protection.',
    attack: 0,
    defence: 25,
    state: 'none',
    price: '1000',
  },
  {
    id: 9,
    uuid: uuidv4(),
    name: 'Nano Suit',
    desc: 'Nano Suit provides ultimate protection against radiation.',
    attack: 0,
    defence: 25,
    state: 'none',
    price: '1000',
  },
  {
    id: 10,
    uuid: uuidv4(),
    name: 'DOOMSLAYER',
    desc: 'No description needed...',
    attack: 0,
    defence: 25,
    state: 'none',
    price: '100000',
  },
];
