export default [
    {
        id: 1,
        name: 'Fly',
        enemyHealth: 25,
        attack: 2,
        defense: 1,
        exp: 25,
        money: 0,
    },
    {
        id: 2,
        name: 'Mutated Rat',
        enemyHealth: 50,
        attack: 5,
        defense: 2,
        exp: 50,
        money: 0,
    },
    {
        id: 3,
        name: 'Dog',
        enemyHealth: 100,
        attack: 7,
        defense: 5,
        exp: 100,
        money: 0,
    },
    {
        id: 4,
        name: 'Ghoul',
        enemyHealth: 250,
        attack: 12,
        defense: 8,
        exp: 125,
        money: 15,
    },
    {
        id: 5,
        name: 'Raider',
        enemyHealth: 250,
        attack: 15,
        defense: 10,
        exp: 150,
        money: 100,
    },
    {
        id: 6,
        name: 'Psychopath',
        enemyHealth: 500,
        attack: 20,
        defense: 10,
        exp: 150,
        money: 100,
    },
    {
        id: 7,
        name: 'Mutant',
        enemyHealth: 1000,
        attack: 45,
        defense: 45,
        exp: 1000,
        money: 250,
    },
  ];
  