import { v4 as uuidv4 } from 'uuid';
export default [
  {
    id: 0,
    uuid: uuidv4(),
    name: 'Hands',
    desc: 'Hands is a great melee weapon. It is used for all sorts of combat.',
    attack: 1,
    defence: 0,
    state: 'none',
    price: '-1',
  },
  {
    id: 1,
    uuid: uuidv4(),
    name: 'Knife',
    desc: 'Knife is a great melee weapon. It is used for all sorts of combat.',
    attack: 2,
    defence: 0,
    state: '0',
    price: '5',
  },
  {
    id: 2,
    uuid: uuidv4(),
    name: 'Baseball Bat',
    desc: 'Baseball Bat is a great melee weapon. It is used for bashing enemies.',
    attack: 2,
    defence: 0,
    state: 'none',
    price: '7',
  },
  {
    id: 3,
    uuid: uuidv4(),
    name: 'Fire Axe',
    desc: 'Fire Axe is a great melee weapon. It is used for chopping enemies.',
    attack: 5,
    defence: 0,
    state: 'none',
    price: '10',
  },
  {
    id: 4,
    uuid: uuidv4(),
    name: 'Machete',
    desc: 'Machete is a versatile melee weapon. It is used for slashing and hacking.',
    attack: 6,
    defence: 0,
    state: 'none',
    price: '12',
  },
  {
    id: 5,
    uuid: uuidv4(),
    name: 'Coil Stick',
    desc: 'Coil Stick is a great melee weapon. It is used for all sorts of combat.',
    attack: 10,
    defence: 0,
    state: 'none',
    price: '25',
  },
  {
    id: 6,
    uuid: uuidv4(),
    name: 'Flare Gun',
    desc: 'Flare Gun is a great ranged weapon. It is used for signaling.',
    attack: 12,
    defence: 0,
    state: 'none',
    price: '12',
  },
  {
    id: 7,
    uuid: uuidv4(),
    name: '10mm Pistol',
    desc: '10mm Pistol is a reliable sidearm. It is used for close-range combat.',
    attack: 12,
    defence: 0,
    state: 'none',
    price: '15',
  },
  {
    id: 8,
    uuid: uuidv4(),
    name: 'Revolver',
    desc: 'Revolver is a powerful sidearm. It is used for close-range combat.',
    attack: 15,
    defence: 0,
    state: 'none',
    price: '17',
  },
  {
    id: 9,
    uuid: uuidv4(),
    name: 'Laser Pistol',
    desc: 'Laser Pistol is a powerful sidearm. It is used for close-range combat.',
    attack: 15,
    defence: 0,
    state: 'none',
    price: '20',
  },
  {
    id: 10,
    uuid: uuidv4(),
    name: 'Semi Pistol',
    desc: 'Semi Pistol is a powerful sidearm. It is used for close-range combat.',
    attack: 25,
    defence: 0,
    state: 'none',
    price: '30',
  },
  {
    id: 11,
    uuid: uuidv4(),
    name: 'Flinklock Rifle',
    desc: 'Flinklock Rifle is a powerful ranged weapon. It is used for long-range combat.',
    attack: 12,
    defence: 0,
    state: 'none',
    price: '12',
  },
  {
    id: 12,
    uuid: uuidv4(),
    name: 'Hunting Rifle',
    desc: 'Hunting Rifle is a great ranged weapon. It is used for hunting.',
    attack: 15,
    defence: 0,
    state: 'none',
    price: '15',
  },
  {
    id: 13,
    uuid: uuidv4(),
    name: 'SMG',
    desc: 'SMG is a powerful ranged weapon. It is used for short-range combat.',
    attack: 18,
    defence: 0,
    state: 'none',
    price: '20',
  },
  {
    id: 14,
    uuid: uuidv4(),
    name: 'Assault Rifle',
    desc: 'Assault Rifle is a powerful ranged weapon. It is used for short-range combat.',
    attack: 25,
    defence: 0,
    state: 'none',
    price: '25',
  },
  {
    id: 15,
    uuid: uuidv4(),
    name: 'Tommy Gun',
    desc: 'Tommy Gun is a powerful ranged weapon. It is used for short-range combat.',
    attack: 28,
    defence: 0,
    state: 'none',
    price: '150',
  },
  {
    id: 16,
    uuid: uuidv4(),
    name: 'LMG',
    desc: 'LMG is a powerful ranged weapon. It is used for short-range combat.',
    attack: 30,
    defence: 0,
    state: 'none',
    price: '35',
  },
  {
    id: 17,
    uuid: uuidv4(),
    name: 'Minigun',
    desc: 'Minigun is a powerful ranged weapon. It is used for short-range combat.',
    attack: 34,
    defence: 0,
    state: 'none',
    price: '42',
  },
  {
    id: 18,
    uuid: uuidv4(),
    name: 'Flamethrower',
    desc: 'Flamethrower is a powerful ranged weapon. It is used for short-range combat.',
    attack: 40,
    defence: 0,
    state: 'none',
    price: '48',
  },
  {
    id: 19,
    uuid: uuidv4(),
    name: 'Rocket Launcher',
    desc: 'Rocket Launcher is a heavy lancher weapon. It is used for crushing enemies.',
    attack: 50,
    defence: 0,
    state: 'none',
    price: '50',
  },
  {
    id: 20,
    uuid: uuidv4(),
    name: 'Santa Gloves',
    desc: 'Santa Gloves OMG!!!',
    attack: 100,
    defence: 0,
    state: 'none',
    price: '100000',
  },
];
