export default [
  {
    id: 1,
    name: 'Tunnel Access',
    desc: 'We need to gain Access to the Tunnels to get to the other side of the city. We need to find a way to get in.',
    exp: 50,
    money: 50,
    duration: 5000,
    progress: 0,
    state: 'not-started',
    disabled: false,
    lat: 51.5150,
    lon: -0.0883,
    reward: [1],
    rewardChance: 0.05,
  },
  {
    id: 2,
    name: 'Gateway to the City',
    desc: 'The Settlement is surrounded by a wall. We need to find a way to get through the gate.',
    exp: 250,
    money: 500,
    duration: 10000,
    progress: 0,
    state: 'not-started',
    disabled: false,
    lat: 51.5137,
    lon: -0.0983,
    reward: [3],
    rewardChance: 0.02,
  },
  {
    id: 3,
    name: 'Clock Tower',
    desc: 'Seek shelter for the night in the Clock Tower.',
    exp: 1000,
    money: 500,
    duration: 10000,
    progress: 0,
    state: 'not-started',
    disabled: false,
    lat: 51.5099,
    lon: -0.0768, 
    reward: [1],
    rewardChance: 0.15,
  },
  {
    id: 4,
    name: 'Dunvick Castle',
    desc: 'We need to find a way to get into the Castle to find the King.',
    exp: 1200,
    money: 1000,
    duration: 20000,
    progress: 0,
    state: 'not-started',
    disabled: false,
    lat: 51.5015,
    lon: -0.0762,
    reward: [2],
    rewardChance: 0.0010,
  },
];