export default [
  {
    id: 1,
    name: 'Tunnel Access',
    desc: 'We need to gain Access to the Tunnels to get to the other side of the city. We need to find a way to get in.',
    exp: 5000,
    money: 50,
    duration: 5000,
    progress: 0,
    state: 'not-started',
    disabled: false,
    reward: [1, 2, 3],
    rewardChance: 0.18,
    armorReward: [1],
    armorRewardChance: 0.05,
    levelRequirement: 1,
  },
  {
    id: 2,
    name: 'Gateway to the City',
    desc: 'The Settlement is surrounded by a wall. We need to find a way to get through the gate.',
    exp: 12500,
    money: 500,
    duration: 10000,
    progress: 0,
    state: 'not-started',
    disabled: false,
    reward: [3],
    rewardChance: 0.5,
    armorReward: [1],
    armorRewardChance: 0.05,
    levelRequirement: 2,
  },
  {
    id: 3,
    name: 'Clock Tower',
    desc: 'Seek shelter for the night in the Clock Tower.',
    exp: 20000,
    money: 500,
    duration: 10000,
    progress: 0,
    state: 'not-started',
    disabled: false,
    reward: [1],
    rewardChance: 0.05,
    armorReward: [1],
    armorRewardChance: 0.05,
    levelRequirement: 3,
  },
  {
    id: 4,
    name: 'Dunvick Castle',
    desc: 'We need to find a way to get into the Castle to find the King.',
    exp: 25000,
    money: 1000,
    duration: 20000,
    progress: 0,
    state: 'not-started',
    disabled: false,
    reward: [2],
    rewardChance: 0.5,
    armorReward: [1],
    armorRewardChance: 0.5,
    levelRequirement: 4,
  },
  {
    id: 5,
    name: 'Abandoned Warehouse',
    desc: 'Search the Abandoned Warehouse for supplies and weapons.',
    exp: 15000,
    money: 750,
    duration: 15000,
    progress: 0,
    state: 'not-started',
    disabled: false,
    reward: [4, 5],
    rewardChance: 0.3,
    armorReward: [2],
    armorRewardChance: 0.1,
    levelRequirement: 5,
  },
  {
    id: 6,
    name: 'Mutant Hideout',
    desc: 'Infiltrate the Mutant Hideout and eliminate the mutant leader.',
    exp: 30000,
    money: 1500,
    duration: 25000,
    progress: 0,
    state: 'not-started',
    disabled: false,
    reward: [6, 7],
    rewardChance: 0.6,
    armorReward: [3],
    armorRewardChance: 0.2,
    levelRequirement: 6,
  },
  {
    id: 7,
    name: 'Forgotten Bunker',
    desc: 'Explore the Forgotten Bunker and recover the lost artifacts.',
    exp: 40000,
    money: 2000,
    duration: 30000,
    progress: 0,
    state: 'not-started',
    disabled: false,
    reward: [2, 6],
    rewardChance: 0.8,
    armorReward: [4],
    armorRewardChance: 0.3,
    levelRequirement: 7,
  },
  {
    id: 8,
    name: 'Radioactive Wasteland',
    desc: 'Venture into the Radioactive Wasteland and collect rare resources.',
    exp: 50000,
    money: 2500,
    duration: 35000,
    progress: 0,
    state: 'not-started',
    disabled: false,
    reward: [4, 7],
    rewardChance: 0.7,
    armorReward: [5],
    armorRewardChance: 0.4,
    levelRequirement: 8,
  },
];
