import { v4 as uuidv4 } from 'uuid';

export default [
  {
    id: 0,
    uuid: uuidv4(),
    name: 'None',
    desc: 'None',
    state: 'none',
    price: '-1',
    quantity: 0,
  },
  {
    id: 1,
    uuid: uuidv4(),
    name: 'Wood Scrap',
    desc: 'Wood Scrap is a piece of wood that can be used to craft weapons.',
    state: 'none',
    price: '2',
    quantity: 0,
  },
  {
    id: 2,
    uuid: uuidv4(),
    name: 'Steel Scrap',
    desc: 'Steel Scrap is a piece of steel that can be used to craft weapons.',
    state: 'none',
    price: '5',
    quantity: 0,
  },
  {
    id: 3,
    uuid: uuidv4(),
    name: 'Plastic Scrap',
    desc: 'Plastic Scrap can be melted and molded into various items.',
    state: 'none',
    price: '3',
    quantity: 0,
  },
  {
    id: 4,
    uuid: uuidv4(),
    name: 'Gasoline',
    desc: 'Gasoline is a flammable liquid that can be used to power vehicles or create explosives.',
    state: 'none',
    price: '4',
    quantity: 0,
  },
  {
    id: 5,
    uuid: uuidv4(),
    name: 'Cloth Scraps',
    desc: 'Cloth Scraps are useful for creating makeshift bandages or clothing.',
    state: 'none',
    price: '2',
    quantity: 0,
  },
  {
    id: 6,
    uuid: uuidv4(),
    name: 'Electronic Parts',
    desc: 'Electronic Parts are essential for repairing or creating electronic devices.',
    state: 'none',
    price: '10',
    quantity: 0,
  },
  {
    id: 7,
    uuid: uuidv4(),
    name: 'Ammunition',
    desc: 'Ammunition is essential for using firearms.',
    state: 'none',
    price: '20',
    quantity: 0,
  },
  {
    id: 8,
    uuid: uuidv4(),
    name: 'Fuel',
    desc: 'Fuel is necessary for running vehicles and generators.',
    state: 'none',
    price: '25',
    quantity: 0,
  },
  {
    id: 9,
    uuid: uuidv4(),
    name: 'Oil',
    desc: 'Oil is a valuable resource that can be used for various purposes, such as lubricating machinery or creating fuel.',
    state: 'none',
    price: '12',
    quantity: 0,
  },
  {
    id: 10,
    uuid: uuidv4(),
    name: 'Battery',
    desc: 'Batteries are essential for powering electronic devices.',
    state: 'none',
    price: '15',
    quantity: 0,
  },
];
